all: barb wiz rog game

barb:
	gcc barbarian.c -o barbarian -lrt -pthread -g -Wall

wiz:
	gcc wizard.c -o wizard -lrt -pthread -g -Wall

rog:
	gcc rogue.c -o rogue -lrt -pthread -g -Wall

game:
	gcc game.c dungeon_x86_64.o -o my_executable -lrt -pthread -g -Wall

clean:
	rm *.o barb wiz rog game
